version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Building...
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: node_modules_{{ checksum package.json }}
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: node_modules_{{ checksum package.json }}
      - run:
          name: Linting...
          command: npm run lint
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: node_modules_{{ checksum package.json }}
      - run:
          name: Testing...
          command: npm run test
  publish:
    branches:
      only: master
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: node_modules_{{ checksum package.json }}
      - run:
          name: Publishing...
          command: npx semantic-release

workflows:
  version: 2
  main:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - publish:
          requires:
            - test